version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - INITIAL_USER_EMAIL=${INITIAL_USER_EMAIL}
      - INITIAL_USER_NAME=${INITIAL_USER_NAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - USE_TLS=${USE_TLS}
    networks:
      - network

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    networks:
      - network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - network

volumes:
  db-data:
    driver: local

networks:
  network:
    driver: bridge
