version: '3'

services:
  backend:
    ports:
      - "8001:8000"

  frontend:
    ports:
      - "3001:3000"

  db:
    ports:
      - "3307:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025"
      - "8026:8025"
    networks:
      - network

networks:
  network:
    driver: bridge
