version: '3'

services:
  backend:
    volumes:
      - ./backend:/app

  frontend:
    volumes:
      - ./frontend:/front

  db:
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./doc/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

volumes:
  db-data:
    driver: local

networks:
  network:
    driver: bridge
