name: Playwright-Docker-Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

      - name: Run Playwright Tests
        run: |
          npm install
          npm run test

      - name: Shutdown Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml down
